config/routes.rb
Rails.application.routes.draw do
  
devise_for :users

resources :books do 
  resources :reviews, only: [ :create]
  resources :permissions, only: [:create]


end

resources :permissions, only: [:create] do
  member do
    patch :approve
    patch :reject
  end
end


resources :admin


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, :author, :description, presence: true
    has_many :reviews, dependent: :destroy
    belongs_to :user
    has_many :permissions, dependent: :destroy
    has_one_attached :pdf
    has_one_attached :image
    validates :pdf, presence: true
    validates :image, presence: true
end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :status, inclusion: {in: ['pending','approved','rejected']}
end

app/models/review.rb
class Review < ApplicationRecord
  validates :rating, :comment, presence: true
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :permissions, dependent: :destroy

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    before_action :authenticate_user!
    before_action :require_admin        
  def index
    @books=Book.all
  end
  def show
    @book = Book.find(params[:id])
    @reviews = @book.reviews
  end

  def require_admin
    unless current_user.admin?
      redirect_to root_path, alert: "Access denied. Admins only."
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  
  allow_browser versions: :modern

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :name , :number])
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]
  
  def index
    @books=Book.includes(:user, :permissions).order(created_at: :desc).page(params[:page]).per(4)
  end

  def show
    @book=Book.find(params[:id])
    if @book.user==current_user || Permission.exists?(user: current_user,book: @book,status: 'approved')
    @review=@book.reviews.build
    @reviews = @book.reviews
    else 
      redirect_to books_path, alert: "you need permission to view book"
    end
  end

  def new
    @book = current_user.books.new
  end

  def create
    @book = current_user.books.new(book_params)
    if @book.save
      redirect_to books_path
    else 
      render :new
    end
  end

  def edit
    @book=current_user.books.find(params[:id])
  end

  def update
    @book=current_user.books.find(params[:id])
    if @book.update(book_params)
      redirect_to books_path
    else
      render :edit
  end
end

 def destroy
  if current_user.admin?
    @book = Book.find(params[:id])
  else
    @book = current_user.books.find(params[:id])
  end

  @book.destroy
  redirect_to books_path, notice: "Book deleted"
end
  
  private
  def book_params
    params.require(:book).permit(:title,:author,:description,:pdf,:image)
  end

end

app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController
before_action :authenticate_user!
  def create
    @book=Book.find(params[:book_id])
    permission=current_user.permissions.find_or_initialize_by(book:@book)
    permission.status ="pending"
    if permission.save 
      redirect_to book_path(@book), notice: "Request sent to book owner"
    else 
      redirect_to books_path, alert: "unable to send request"
    end
  end

  def approve
    permission=Permission.find(params[:id])
    if permission.book.user==current_user
      permission.update(status: 'approved')
      redirect_to book_path(permission.book), notice: "access approved"
    else
      redirect_to books_path
    end
  end

  def reject
    permission=Permission.find(params[:id])
    if permission.book.user==current_user
      permission.update(status: 'rejected')
      redirect_to book_path(permission.book), notice: "access rejected"
    else 
      redirect_to books_path
    end
 end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    
    @book=Book.find(params[:book_id])
    @review = @book.reviews.build(review_params)
    @review.user = current_user
    if @review.save
      redirect_to @book
    else 
       render "books/show"
      end
  end


  def review_params
    params.require(:review).permit(:rating,:comment)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/index.html.erb
<h1>Admin Dashboard</h1>
<h2 class="mb-4"><br>All Books</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Title</th>
      <th>Author</th>
      <th>Email</th>
      <th>View</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each_with_index do |book, index| %>
      <tr>
        <th scope="row"><%= index + 1 %></th>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.user.email %></td>
        <td> <%= link_to "View", admin_path(book), class: "btn btn-outline-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/show.html.erb
<br><br><br><div class="d-flex justify-content-end mt-3">
 <%= button_to "Delete", book_path(@book), method: :delete, class: "btn btn-outline-danger btn-lg" %>
</div>

<h1><%= @book.title %></h1>
<p><strong>Author:</strong> <%= @book.author %></p>
<p><strong>Description:</strong> <%= @book.description %></p>
<p><strong>Uploaded By:</strong> <%= @book.user.email %></p>

<h2 class="mt-4">Book Reviews</h2>

<% if @book.reviews.any? %>
  <% @book.reviews.each do |review| %>
      <p><strong>Rating:</strong> <%= review.rating %></p>
      <p><strong>Comment:</strong> <%= review.comment %></p>
      <p><small><strong>By:</strong> <%= review.user.email %></small></p>
  <% end %>
<% else %>
  <p>No reviews yet for this book.</p>
<% end %>

<%= link_to "Back to Admin Dashboard", admin_index_path, class: "btn btn-outline-primary mt-3" %>


app/views/books/edit.html.erb
<div class="container">
 <div class="row justify-content-center">
   <div class="col-5">
     <div class="mt-3">
<%= form_with model:@book do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>
<br>
    <%= form.label :author %>
    <%= form.text_field :author %>
<br>
    <%= form.label :description %>
    <%= form.text_field :description %>
<br>
    <%= form.label :image %>
    <%= form.file_field :image %>
<br>
    <%= form.button %>
    <% end %>

<%= button_to "Delete", @book, method: :delete %>

</div>

app/views/books/index.html.erb
<%if user_signed_in? %>
<br>
<div class="d-flex  align-items mt-5 pt-3">

<div class="bg-dark text-white text-center mx-auto p-1  rounded " style="width: fit-content;" >
<% if user_signed_in? %>
    <h2>Welcome <%= current_user.name %></h2>
<% end %>
</div>
  <div>
    <%= link_to "Add Book", new_book_path, class: "btn btn-outline-primary btn-lg" %>
  </div>
</div>
<% end %>


<div class="container text-center mt-5 pt-4">   
<div class="row p-4">
<% @books.each do |book| %>
    <div class="col-md-3 mb-4">
      <div class="card h-100 d-flex flex-column" style="width: 18rem;">

      <% if book.image.attached? %>
      <%= image_tag book.image, alt: "Cover image", class: "card-img-top img-thumbnail", style: "height: 300px; object-fit: cover;" %>
      <% end %>
      
        <div class="card-body text-start">
          <%= link_to book_path(book), class: "text-decoration-none" do %>
            <h2 class="card-title"><%= book.title %></h2>
            <h4 class="card-subtitle mb-2 text-black">Author: <%= book.author %></h4>
            <p class="card-text text-muted"><%= book.description %></p>
          <% end %>
        </div>
<div class="mt-auto p-3">
  <% if user_signed_in? %>
    <% if book.user==current_user %>
      <%= link_to "View Book", book_path(book),class: "text-decoration-none" %><br>
    <% elsif Permission.exists?(user: current_user, book: book, status: 'approved') %>
      <%= link_to "View Book", book_path(book),class: "text-decoration-none" %><hr>
    <% elsif Permission.exists?(user: current_user, book: book, status: 'pending') %>
      <h2 class="text-warning mt-2">Request Pending</h2>
    <% elsif Permission.exists?(user: current_user, book: book, status: 'rejected') %>
      <h2 class="text-danger mt-2">Request Rejected</h2>

    <% else %>
      <%= button_to "Request Access", book_permissions_path(book), method: :post %>
    <% end %>

    <% else %>
        <%= link_to "Login to request access", new_user_session_path, class: "btn btn-outline-primary " %>
    <% end %>
          </div>
        </div>  
    </div>
    <% end  %>
  </div>
</div>



<br>

<%= paginate @books %>

app/views/books/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-5">
      <div class="mt-5 pt-3">
        <h1> New Book </h1>
      </div>
<%= form_with model:@book do |form| %>
    <div class="form-group row mt-3">
         <%= form.label :title %>
         <%= form.text_field :title, class: "form-control" %>
    </div>
<br>
   <div class="form-group row mt-3">
        <%= form.label :author %>
        <%= form.text_field :author, class: "form-control" %>
    </div>
<br>
   <div class="form-group row mt-3">
       <%= form.label :description %>
       <%= form.text_field :description, class: "form-control" %>
    </div>
<br>
    <div class="form-group row mt-3">
         <%= form.label :pdf %>
         <%= form.file_field :pdf, class: "form-control" %>
    </div>
<br>
    <div class="form-group row mt-3">
       <%= form.label :image %>
       <%= form.file_field :image, class: "form-control" %>
    </div>
<br>
    <div class="form-group row mt-3">
        <%= form.button "Create Book",class: "btn btn-primary" %>
    </div>
    <% end %>


    

app/views/books/show.html.erb
<div class="container w-100% ">

<% if current_user == @book.user %> 
<div style="position: relative;">
  <div style="position: absolute; top: 60px; right: -110px;">
    <%= link_to "Edit Book", edit_book_path(@book) , class: "btn btn-primary mt-2 btn-lg" %>
  </div>
</div>
<% end %>

 <div class="row justify-content-corner">
   <div class="col-5">
     <div class="mt-5 pt-5 text-start">
<h2>Title: <%= @book.title %></h2>
<h4>Author: <%= @book.author %></h2>
<h5>Description: <br><p class="text-secondary"><%= @book.description %></h2>

<br><% if @book.pdf.attached? %>
    <%#= link_to "View Book", url_for(@book.pdf), target: "_blank",class: "text-decoration-none",class: "btn btn-primary btn-sm mt-2"   %>
    <div class="embed-responsive embed-responsive-21by9">
      <iframe class="embed-responsive-item"style="width:550px; height:500px;" src="<%= url_for(@book.pdf) %>"></iframe>
    </div>
<% end %>

<br>
<% if user_signed_in? && current_user != @book.user %>
  <%= render "reviews/form" %> 
<% end %>


<h2>Book Reviews</h2>
<% @book.reviews.each do |review| %>
    <h4>Rating: <%= review.rating %></h4>
    <h4>Comment: <%= review.comment %></h4>
    <br>
<% end %>

<% if current_user == @book.user %>
<% @book.permissions.where(status: 'pending').each do |permission| %>
  <h2><b> Pending Requests <b></h2>
  <h4>User: <%= permission.user.email %></h4>
  <%= button_to "Approve", approve_permission_path(permission),method: :patch,class: "btn btn-primary btn-sm mt-2" %><br>
  <%= button_to "Reject", reject_permission_path(permission),method: :patch,class: "btn btn-primary btn-sm mt-2" %>
  <% end %>
  </div>
  <% end %>






<!-- ifaram -->

app/views/layouts/_nav.html.erb
<nav class="navbar bg-dark border-bottom border-body fixed-top" data-bs-theme="dark">
  <div class="container-fluid">
  <div class="fs-2 text-start">
  <a class="navbar-brand" href="#"><%= link_to "Book", books_path,class:"text-decoration-none text-white" %></a>
  </div>
  <% if user_signed_in? %>
  <div class="d-flex ms-auto gap-2">
    <% if current_user.admin? %>
      <%= link_to "Admin Dashboard", admin_index_path, class: "btn btn-outline-warning me-2" %>
    <% end %>
    <%= button_to "Log Out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class:"btn btn-outline-danger" %>
  <% else %>
  <div class="d-grid gap-2 d-md-flex justify-content-md-end" class="d-grid gap-2 d-md-block">
    <h3><%= link_to "Login", new_user_session_path, class: "btn btn-outline-primary "  %></h3>
    <h3><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-primary " %></h3>
  </div>
<% end %>
  </div>
</nav>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Book Reviewer" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>
    

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  

  <body>
  <% if notice %>
    <div class="alert alert-success mt-5 " role="alert">
    <p class="notice"><%= notice %></p>
    </div>
  <% elsif alert %>
    <div class="alert alert-danger mt-5 " role="alert">
    <p class="alert"><%= alert %></p>
    </div>
  <% end %>

  <%= render "layouts/nav" %>
    <%= yield %>
  </body>
</html>

app/views/permissions/approve.html.erb
<h1>Permissions#approve</h1>
<p>Find me in app/views/permissions/approve.html.erb</p>

app/views/permissions/create.html.erb
<h1>Permissions#create</h1>
<p>Find me in app/views/permissions/create.html.erb</p>

app/views/permissions/reject.html.erb
<h1>Permissions#reject</h1>
<p>Find me in app/views/permissions/reject.html.erb</p>

app/views/reviews/_form.html.erb
<h2>Add Review</h2>
<%= form_with(model: [@book, @review]) do |form| %>
    <%= form.label :rating %><br>
    <%= form.number_field :rating %>
    <%= form.label :comment %>
    <%= form.text_field :comment %><br>
    
    <br><%= form.submit  %>
<% end %>